---
dependency:
  name: galaxy

driver:
  name: "{{ cookiecutter.molecule_driver }}"

platforms:
  {% if cookiecutter.molecule_driver == 'vagrant' %}
  - name: ubuntu
    box: ubuntu/bionic64
    memory: 1024
    cpus: 2
  {% elif cookiecutter.molecule_driver in ['docker', 'podman'] %}
  - name: ubuntu
    image: "ubuntu:bionic"
    privileged: true
    pre_build_image: true
  {% endif %}

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: "{{ cookiecutter.molecule_verifier }}"